apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-kube-news-registration
spec: 
  replicas: 1
  template:
    metadata:
      labels: 
        app: kube-news-registration
      name: kube-news-registration
    spec:
      containers:
        - name: kube-news-registration-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-map-kube-news-registration
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessao
              mountPath: /tmp
          livenessProbe: 
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
              httpGet:
                path: /inserir_noticias.php
                port: 80
              periodSeconds: 10
              failureThreshold: 5
              initialDelaySeconds: 3
      volumes:
        - name: imagens
          persistentVolumeClaim:
              claimName: pvc-kube-news-registration-imagens
        - name: sessao
          persistentVolumeClaim:
              claimName: pvc-kube-news-registration-sessao
  selector:
    matchLabels:
      app: kube-news-registration
  serviceName: svc-kube-news-registration