apiVersion: v1
kind: Pod
metadata:
  name: kube-news-db
  labels:
    app: kube-news-db
spec:
  containers:
    - name: kube-news-db-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306