apiVersion: v1
kind: Pod
metadata:
  name: pod-demo-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: pv-demo-sc
  volumes:
    - name: pv-demo-sc
      persistentVolumeClaim:
        claimName: pvc-sc-demo