apiVersion: v1
kind: Pod
metadata:
  name: pod-demo-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: pv-demo
  volumes:
    - name: pv-demo
      persistentVolumeClaim:
        claimName: pvc-demo